Attempting to make EstatioPartition be subclass, suppressing ApplicationTenancies#listAll() action.
However:
- the vetoing of menu services would seem not to work?
- executing EstatioPartitions#listAll(...) returned stacktrace (see below) which suggests either an issue with Isis or (perhaps) bad annotations on EstatioPartition.

So... gonna simplify and discard EstatioPartition.

 ... 66 more
Caused by: javax.jdo.JDOFatalInternalException: The key value passed to construct a SingleFieldIdentity of type "javax.jdo.identity.StringIdentity" for class "org.estatio.dom.instance.EstatioPartition" is of an incorrect type ("javax.jdo.identity.StringIdentity") - should be "String".
NestedThrowables:
org.datanucleus.exceptions.NucleusException: The key value passed to construct a SingleFieldIdentity of type "javax.jdo.identity.StringIdentity" for class "org.estatio.dom.instance.EstatioPartition" is of an incorrect type ("javax.jdo.identity.StringIdentity") - should be "String".
 at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:591)
 at org.datanucleus.api.jdo.JDOPersistenceManager.newObjectIdInstance(JDOPersistenceManager.java:1622)
 at org.datanucleus.api.jdo.JDOPersistenceManager.getObjectById(JDOPersistenceManager.java:1740)
 at org.apache.isis.objectstore.jdo.datanucleus.DataNucleusObjectStore.loadPojo(DataNucleusObjectStore.java:402)
 at org.apache.isis.core.runtime.persistence.adaptermanager.PojoRecreatorForDataNucleus.recreatePojo(PojoRecreatorForDataNucleus.java:36)